apiVersion: skaffold/v2beta23
kind: Config
build:
  local:
    useBuildkit: true
  artifacts:
    - image: kubeshop/testkube-executor-keptn # Todo: Replace this with your image name
      docker:
        dockerfile: Dockerfile
        buildArgs:
          debugBuild: true
deploy:
  helm:
    flags:
      upgrade: ["--reuse-values", "--install"]
    releases:
      - name: keptn-service-template-go
        namespace: keptn
        artifactOverrides:
          image: kubeshop/testkube-executor-keptn # Todo: Replace this with your image name
        imageStrategy:
          helm: { }
        overrides:
          distributor:
            image:
              tag: 0.12.0
          resources:
            limits:
              memory: 512Mi
        chartPath: chart
